databases:
  - name: prtracker
    databaseName: prtracker
    user: prtracker

services:
  - type: web
    name: prtracker
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: prtracker
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
